### ISSUE TITLE
src/main/resources/certs

### ISSUE THREAD

**Issue by martinschultzkristensen** [puzzle/zeus#7]
Hi,

I'm on a rasperry pi running Raspiblitz. I cannot find the src/main/resources/certs dir.
Is it one i shall make from root or can anyone elaborate?

Thanks.

**Comment by guggero** [comment]
Hi

Sorry, this was not fully correct in the README. It should go into the folder `backend/src/main/resources/certs` of your local copy of Zeus that you cloned from GitHub.

Fixed with 99f5079.

**Comment by martinschultzkristensen** [comment]
Thanks.
